name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray
  - dask
  - distributed
  - dask-kubernetes
  - gcsfs
  - zarr
  - matplotlib
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - jupyterlab_launcher
  - jupyter_client
  - ipywidgets
  - graphviz
  - nodejs
  - scikit-image
  - scikit-learn
  - dask-ml
  - pip
  - pip:
    - kubernetes
    - graphviz
    - intake-xarray
    - jupyter-server-proxy
    - git+https://github.com/xgcm/xgcm.git
